# Generated by Django 2.2.16 on 2022-03-04 08:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORIES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', 'Введены неправильные знаки!')])),
            ],
        ),
        migrations.CreateModel(
            name='GENRES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Жанр')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='review of title')),
                ('score', models.IntegerField(verbose_name='score')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='year of writing')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='TITLES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название Произведения')),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=200)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='review.CATEGORIES')),
                ('genre', models.ManyToManyField(blank=True, related_name='genre', to='review.GENRES')),
            ],
        ),
    ]
