# Generated by Django 2.2.16 on 2022-03-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20220304_0850'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review for title',
        ),
    ]
