# Generated by Django 2.2.16 on 2022-03-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment on review',
        ),
    ]
